language: csharp
mono: none
dotnet: 2.1.301
before_script: cd RestAPI
script:
 - dotnet restore
deploy:
   provider: cloudfoundry
   username: jhonatantiradotiradodeep@gmail.com
   password:
    secure: "xxxxxxxxxxxxxxxxxxxx"
   api: https://api.run.pivotal.io
   organization: kipubit
   space: development